version: '3.8'
services:
  raceapp:
    image: bahhasekke176/raceapp:latest
    deploy:
      replicas: 1
    ports: 
    - published: 5000
      target: 5000
    environment: 
      DATABASE_URI: ${ADAM_DATABASEURI}
      SECRET: ${MY_SECRET_KEY} 
  mysql_container:
    image: mysql:5.7
    deploy:
      replicas: 1
    ports:
    - published: 3306
      target: 3306
    environment:
     MYSQL_ROOT_PASSWORD: ${MY_PASSWORD} 
     MYSQL_DATABASE: ${MY_DATABASE_NAME}
    volumes: 
    - type: volume
      source: raceapp
      target: /var/lib/mysql
  nginx:
    image: nginx:latest
    volumes:
    - type: bind
      source: nginx/nginx.conf
      target: /etc/nginx/nginx.conf
    deploy:
      replicas: 1
    ports:
    - published: 80
      target: 80 

volumes: 
 raceapp: 