version: '3.8'
services:
  raceapp:
    image: bahhasekke176/raceapp:latest
    deploy:
      replicas: 1
    ports: 
    - published: 5000
      target: 5000
    environment: 
      DATABASE_URI: "mysql+pymysql://root:password123@mysql_container:3306/racedb"
  mysql_container:
    image: mysql:5.7
    deploy:
      replicas: 1
    ports:
    - published: 3306
      target: 3306
    environment:
     MYSQL_ROOT_PASSWORD: password123 
     MYSQL_DATABASE: racedb
    volumes: 
    - type: volume
      source: raceapp
      target: /var/lib/mysql
  nginx:
    image: nginx:latest
    volumes:
    - type: bind
      source: ./nginx/nginx.conf
      target: /etc/nginx/nginx.conf
    deploy:
      replicas: 1
    ports:
    - published: 80
      target: 80 

volumes: 
 raceapp: 